// Data reducer types
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const STOP_FETCHING = 'STOP_FETCHING';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const LIST_TOP_RESTAURANTS = 'LIST_TOP_RESTAURANTS';
export const LIST_COUNTRY_RESTAURANTS = 'LIST_COUNTRY_RESTAURANTS';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';


//UI Reducer Types
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';